### ISSUE TITLE
Playback doesn't work

### ISSUE THREAD

**Issue by LukiVuitton** [andygruber/songseeker#14]
Testing on the https://songseeker.grub3r.io/ website I wasn't able to start a song. The Scan works and I can see the song infos but there's no sound when pressing play.

**Comment by andygruber** [comment]
Hey there. I just tested it today with no issues. I suggest to try to open youtube on the same browser and try to play a video there. Maybe it is something related to your device/network/browser/browser-addon .

You can also try to use a browser with default settings without add-blocker.

**Comment by andygruber** [comment]
Closing this one since there is no new information
